### ISSUE TITLE
前辈您好，我在训练GANet时出现了错误

### ISSUE THREAD

**Issue by flyxuexi** [xxxupeng/ADL#3]
File "/home/fly/stereo/adl/backbones/GANet/libs/GANet/functions/GANet.py", line 3, in <module>
    from ..build.lib import GANet
ImportError: cannot import name 'GANet' from 'backbones.GANet.libs.GANet.build.lib' (unknown location)，好像是没有办法识别GANet.xxxx.so文件，请问该怎么解决呀，感谢！

**Comment by xxxupeng** [comment]
需要先参照 [GANet](https://github.com/feihuzhang/GANet)  readme 中 how to use'  进行编译。

**Comment by flyxuexi** [comment]
> 需要先参照 [GANet](https://github.com/feihuzhang/GANet) readme 中 how to use' 进行编译。

好的，谢谢你

**Comment by flyxuexi** [comment]
> 需要先参照 [GANet](https://github.com/feihuzhang/GANet) readme 中 how to use' 进行编译。

前辈，打扰了，我给您的邮箱发了一封信息，能麻烦看一下吗~
